# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: fabric-chaincode-go

on:
  pull_request:
    branches:
    - main
    - release-*


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        clean: true
    - name: install Tools
      run: |
        pushd ci/tools
        go install golang.org/x/lint/golint
        go install golang.org/x/tools/cmd/goimports
        popd

    - name: Vet and lint
      run: ci/scripts/lint.sh

    - name: Check Licenses
      run: license-check-and-add check -f .azure-pipelines/resources/license-config.json

    - name: Run tests
      run: go test -race ./...
                    
    - run: cd internal/functionaltests && godog
      name: Run functional tests

    - run: .azure-pipelines/scripts/tutorial-checks.sh
      name: Check tutorial contents                    

